export const taskQueryKeys = {
  all: ['tasks'] as const,
  list: (projectId: string) => ['tasks', projectId] as const,
  paginated: (projectId: string) => ['tasks', 'paginated', projectId] as const,
  paginatedAll: ['tasks', 'paginated'] as const,
  /** Canonical bridge-backed task snapshot shared by every task consumer. */
  snapshot: (scope: string) => ['tasks', 'snapshot', scope] as const,
  snapshotAll: ['tasks', 'snapshot'] as const,
  detail: (taskId: string) => ['tasks', taskId] as const,
  single: (taskId: string, projectId: string | null) => ['tasks', 'single', taskId, projectId ?? '__no-project__'] as const,
  statusCounts: (projectId: string) => ['task-status-counts', projectId] as const,
  statusCountsAll: ['task-status-counts'] as const,
  result: (taskId: string) => ['task-result', taskId] as const,
  cascadedError: (taskId: string) => ['cascaded-task-error', taskId] as const,
  generationMapping: (generationId: string) => ['generation-task-mapping', generationId] as const,
  taskMapping: (taskId: string) => ['task-generation-mapping', taskId] as const,
  pendingGeneration: (shotId: string) => ['pending-generation-tasks', shotId] as const,
  pendingSegment: (shotId: string) => ['pending-segment-tasks', shotId] as const,
  activeJoinClips: (shotId: string) => ['active-join-clips-task', shotId] as const,
  allTypes: ['all-task-types'] as const,
  typesConfig: ['task-types-config'] as const,
  typesConfigAll: ['task-types-config', 'all'] as const,
  type: (typeId: string) => ['task-type', typeId] as const,
  types: ['task-types'] as const,
  log: (limit: number, page: number, filters: unknown) => ['task-log', limit, page, filters] as const,
} as const;
