/**
 * Compiler Canary — extension-owned DSL compiler that exercises the full
 * M3 public extension contract.
 *
 * The compiler canary:
 * 1. Reads the current timeline via ctx.creative.reader.snapshot()
 * 2. Stores DSL source + source-map data in extension project-data namespace
 *    via ctx.creative.timeline.apply() with project-data.write ops
 * 3. Creates TimelineProposal objects via ctx.creative.proposals.create()
 *    to add, update, or delete generated clips
 * 4. Stamps GeneratedObjectMeta (extensionId, contributionId, provenance,
 *    generatedAt, sourceMapEntryId) on every generated clip/track
 * 5. Proposes add/update/delete operations only for objects it owns
 *    (identified by __generated__ metadata)
 * 6. On cleanup, removes only its own generated objects from the timeline
 *
 * The canary uses ONLY public SDK types from @reigh/editor-sdk. It does not
 * import from video-editor internals (DataProvider, TimelineData, store, etc.).
 *
 * @publicContract
 */

import type {
  TimelineOps,
  TimelineReader,
  TimelineSnapshot,
  TimelinePatch,
  TimelinePatchOperation,
  TimelineProposalInput,
  TimelineProposal,
  ProposalRuntime,
  TimelineClipSummary,
  TimelineTrackSummary,
  GeneratedObjectMeta,
  SourceMapEntry,
  DisposeHandle,
  ExtensionContext,
} from '@reigh/editor-sdk';

// ---------------------------------------------------------------------------
// DSL types
// ---------------------------------------------------------------------------

/** A single clip entry in the compiler canary DSL. */
export interface CanaryDslClip {
  /** Stable ID for the generated clip (used as the timeline clip ID). */
  id: string;
  /** Target track ID (must exist in snapshot). */
  track: string;
  /** Start position in seconds. */
  at: number;
  /** Duration in seconds (hold clip). */
  duration: number;
  /** Clip type, defaults to 'hold'. */
  clipType?: string;
  /** 1-based source line number for source-map linking. */
  sourceLine?: number;
}

/** The compiler canary DSL document. */
export interface CanaryDsl {
  /** DSL format version. */
  version: 1;
  /** Virtual source URI for source-map entries. */
  sourceUri?: string;
  /** Clips to generate. */
  clips: CanaryDslClip[];
}

/** Result returned by the compiler canary after processing a DSL. */
export interface CompilerCanaryResult {
  /** The proposal created (or undefined if the DSL was empty). */
  proposal?: TimelineProposal;
  /** IDs of clips generated/updated by this run. */
  generatedClipIds: string[];
  /** Source-map entry IDs created for this run. */
  sourceMapEntryIds: string[];
}

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

/** Well-known key for GeneratedObjectMeta in clip app data. */
const GENERATED_META_KEY = '__generated__';

/** Project-data key prefix for DSL source storage. */
const DSL_KEY_PREFIX = '__dsl__:';

/** Project-data key prefix for source-map entries. */
const SM_KEY_PREFIX = '__sm__:';

/** Contribution ID used in generated metadata. */
const CANARY_CONTRIBUTION_ID = 'compiler-canary-generator';

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/** Generate a unique ID for source-map entries. */
let _nextSmId = 0;
function generateSmId(): string {
  _nextSmId += 1;
  return `cc-sme-${_nextSmId}-${Date.now().toString(36)}`;
}

/** Current epoch milliseconds. */
function now(): number {
  return Date.now();
}

/**
 * Build a GeneratedObjectMeta record for a clip generated by this canary.
 */
function buildGeneratedMeta(
  extensionId: string,
  sourceMapEntryId?: string,
): GeneratedObjectMeta {
  const meta: GeneratedObjectMeta = {
    extensionId,
    contributionId: CANARY_CONTRIBUTION_ID,
    generatedAt: now(),
  };
  if (sourceMapEntryId) {
    meta.sourceMapEntryId = sourceMapEntryId;
  }
  return meta;
}

/**
 * Serialize a CanaryDsl to a JSON string.
 */
function serializeDsl(dsl: CanaryDsl): string {
  return JSON.stringify(dsl);
}

/**
 * Parse a CanaryDsl from a JSON string.
 */
function parseDsl(raw: string): CanaryDsl | null {
  try {
    const parsed = JSON.parse(raw);
    if (!parsed || typeof parsed !== 'object' || Array.isArray(parsed)) return null;
    if (parsed.version !== 1) return null;
    if (!Array.isArray(parsed.clips)) return null;
    return parsed as CanaryDsl;
  } catch {
    return null;
  }
}

/**
 * Build project-data.write operations for the DSL source.
 */
function buildDslWriteOps(
  extensionId: string,
  dsl: CanaryDsl,
): TimelinePatchOperation[] {
  const sourceUri = dsl.sourceUri ?? `dsl://${extensionId}/main.json`;
  return [
    {
      op: 'project-data.write',
      target: extensionId,
      payload: {
        key: `${DSL_KEY_PREFIX}${sourceUri}`,
        value: serializeDsl(dsl),
        mode: 'replace',
      },
    },
  ];
}

/**
 * Build project-data.write operations for source-map entries.
 */
function buildSourceMapOps(
  extensionId: string,
  dsl: CanaryDsl,
  clipIdToSmId: Map<string, string>,
): TimelinePatchOperation[] {
  const ops: TimelinePatchOperation[] = [];
  const sourceUri = dsl.sourceUri ?? `dsl://${extensionId}/main.json`;

  for (let i = 0; i < dsl.clips.length; i++) {
    const clip = dsl.clips[i];
    const smId = generateSmId();
    clipIdToSmId.set(clip.id, smId);

    const sourceLine = clip.sourceLine ?? i + 3; // approximate line number
    const entry: Record<string, unknown> = {
      id: smId,
      source: extensionId,
      targetId: clip.id,
      targetGranularity: 'clip',
      sourceUri,
      sourceStartLine: sourceLine,
      sourceStartColumn: 0,
      sourceEndLine: sourceLine,
      sourceEndColumn: 0,
      stale: false,
    };

    ops.push({
      op: 'project-data.write',
      target: extensionId,
      payload: {
        key: `${SM_KEY_PREFIX}${smId}`,
        value: entry,
        mode: 'replace',
      },
    });
  }

  return ops;
}

/**
 * Build clip.add operations for each DSL clip entry.
 * Each clip carries generated-object metadata in its app payload.
 */
function buildClipAddOps(
  extensionId: string,
  snapshot: TimelineSnapshot,
  dsl: CanaryDsl,
  clipIdToSmId: Map<string, string>,
): TimelinePatchOperation[] {
  const ops: TimelinePatchOperation[] = [];

  // Build a set of clip IDs already owned by this extension (handled by update/remove)
  const snapshotClips = new Map<string, TimelineClipSummary>();
  for (const c of snapshot.clips) {
    snapshotClips.set(c.id, c);
  }

  for (let i = 0; i < dsl.clips.length; i++) {
    const clip = dsl.clips[i];

    // Skip clips already owned by this extension — they're handled by update/remove
    const existing = snapshotClips.get(clip.id);
    if (existing && isOwnedByExtension(existing, extensionId)) continue;
    const smId = clipIdToSmId.get(clip.id);
    const generatedMeta = buildGeneratedMeta(extensionId, smId);

    ops.push({
      op: 'clip.add',
      target: clip.id,
      order: i,
      payload: {
        track: clip.track,
        at: clip.at,
        clipType: clip.clipType ?? 'hold',
        hold: clip.duration,
        app: {
          [extensionId]: { source: 'compiler-canary' },
          [GENERATED_META_KEY]: generatedMeta,
        },
      },
    });
  }

  return ops;
}

/**
 * Build clip.remove operations for clips that are managed by this extension
 * but are no longer in the DSL.
 */
function buildClipRemoveOps(
  extensionId: string,
  snapshot: TimelineSnapshot,
  dslClipIds: Set<string>,
): TimelinePatchOperation[] {
  const ops: TimelinePatchOperation[] = [];

  for (const clipSummary of snapshot.clips) {
    if (dslClipIds.has(clipSummary.id)) continue;
    if (!isOwnedByExtension(clipSummary, extensionId)) continue;

    ops.push({
      op: 'clip.remove',
      target: clipSummary.id,
    });
  }

  return ops;
}

/**
 * Check whether a clip summary is owned by the given extension.
 * Uses the __generated__ metadata or extension namespace in app data.
 */
function isOwnedByExtension(
  clip: TimelineClipSummary,
  extensionId: string,
): boolean {
  // Check generatedMeta
  if (clip.generatedMeta && clip.generatedMeta.extensionId === extensionId) {
    return true;
  }
  // Check managedBy
  if (clip.managed && clip.managedBy === extensionId) {
    return true;
  }
  return false;
}

/**
 * Build clip.update operations for clips that exist in both the snapshot
 * and the DSL but with different properties.
 */
function buildClipUpdateOps(
  extensionId: string,
  snapshot: TimelineSnapshot,
  dsl: CanaryDsl,
  clipIdToSmId: Map<string, string>,
): TimelinePatchOperation[] {
  const ops: TimelinePatchOperation[] = [];
  const snapshotClips = new Map<string, TimelineClipSummary>();
  for (const c of snapshot.clips) {
    snapshotClips.set(c.id, c);
  }

  for (let i = 0; i < dsl.clips.length; i++) {
    const dslClip = dsl.clips[i];
    const existing = snapshotClips.get(dslClip.id);
    if (!existing) continue; // handled by add
    if (!isOwnedByExtension(existing, extensionId)) continue; // not ours

    const needsUpdate =
      existing.track !== dslClip.track ||
      Math.abs(existing.at - dslClip.at) > 0.001 ||
      Math.abs(existing.duration - dslClip.duration) > 0.001;

    if (needsUpdate) {
      const smId = clipIdToSmId.get(dslClip.id);
      const generatedMeta = buildGeneratedMeta(extensionId, smId);

      ops.push({
        op: 'clip.update',
        target: dslClip.id,
        order: i,
        payload: {
          track: dslClip.track,
          at: dslClip.at,
          hold: dslClip.duration,
          app: {
            [extensionId]: { source: 'compiler-canary' },
            [GENERATED_META_KEY]: generatedMeta,
          },
        },
      });
    }
  }

  return ops;
}

// ---------------------------------------------------------------------------
// Compiler Canary API
// ---------------------------------------------------------------------------

/** Options for the compiler canary. */
export interface CompilerCanaryOptions {
  /** The extension ID that owns generated objects. */
  extensionId: string;
  /** Live TimelineOps adapter (ctx.creative.timeline). */
  timeline: TimelineOps;
  /** Live TimelineReader adapter (ctx.creative.reader). */
  reader: TimelineReader;
  /** Live ProposalRuntime adapter (ctx.creative.proposals). */
  proposals: ProposalRuntime;
}

/**
 * The compiler canary public API.
 *
 * Extensions call `processDsl()` to parse a DSL, store source/source-map data,
 * and emit a TimelineProposal.  They call `cleanupOwnObjects()` to remove all
 * objects generated by this extension from the timeline.
 */
export interface CompilerCanary {
  /**
   * Process a DSL string: parse, snapshot, compute diff, store source +
   * source-map data, and create a TimelineProposal.
   *
   * Returns the result including the proposal and generated clip IDs.
   * Returns null if the DSL is invalid.
   */
  processDsl(dslJson: string): CompilerCanaryResult | null;

  /**
   * Create a proposal that removes all clips owned by this extension
   * from the current timeline.
   */
  cleanupOwnObjects(rationale?: string): CompilerCanaryResult;

  /** The extension ID. */
  readonly extensionId: string;
}

/**
 * Create a compiler canary instance for the given extension.
 *
 * The canary uses only the public creative context services — it never
 * imports or accesses internal timeline stores, DataProvider, or
 * mutation engines.
 */
export function createCompilerCanary(
  options: CompilerCanaryOptions,
): CompilerCanary {
  const { extensionId, timeline, reader, proposals } = options;

  function processDsl(dslJson: string): CompilerCanaryResult | null {
    // 1. Parse DSL
    const dsl = parseDsl(dslJson);
    if (!dsl) return null;

    // 2. Read current timeline snapshot
    const snapshot = reader.snapshot();

    // 3. Build DSL and source-map project-data ops
    const dslOps = buildDslWriteOps(extensionId, dsl);
    const clipIdToSmId = new Map<string, string>();
    const smOps = buildSourceMapOps(extensionId, dsl, clipIdToSmId);

    // 4. Determine which clips need to be added, updated, or removed
    const dslClipIds = new Set(dsl.clips.map((c) => c.id));
    const removeOps = buildClipRemoveOps(extensionId, snapshot, dslClipIds);
    const updateOps = buildClipUpdateOps(extensionId, snapshot, dsl, clipIdToSmId);
    const addOps = buildClipAddOps(extensionId, snapshot, dsl, clipIdToSmId);

    // 5. Write source + source-map data via TimelineOps.apply()
    const dataPatch: TimelinePatch = {
      version: snapshot.baseVersion,
      operations: [...dslOps, ...smOps],
      source: extensionId,
      meta: { kind: 'compiler-canary-data' },
    };

    if (dataPatch.operations.length > 0) {
      timeline.apply(dataPatch);
    }

    // 6. Build the main patch (clip mutations)
    const mainOperations = [...removeOps, ...updateOps, ...addOps];
    const generatedClipIds = [
      ...addOps.map((o) => o.target),
      ...updateOps.map((o) => o.target),
    ];
    const sourceMapEntryIds = [...clipIdToSmId.values()];

    if (mainOperations.length === 0) {
      // No clip changes needed — return result without creating a proposal
      return {
        generatedClipIds,
        sourceMapEntryIds,
      };
    }

    const mainPatch: TimelinePatch = {
      version: snapshot.baseVersion + 1, // account for data patch above
      operations: mainOperations,
      source: extensionId,
      meta: { kind: 'compiler-canary' },
    };

    // 7. Create proposal
    const input: TimelineProposalInput = {
      source: extensionId,
      rationale: `Compiler canary: ${addOps.length} added, ${updateOps.length} updated, ${removeOps.length} removed`,
      patch: mainPatch,
      baseVersion: reader.snapshot().baseVersion,
    };

    const proposal = proposals.create(input);

    return {
      proposal,
      generatedClipIds,
      sourceMapEntryIds,
    };
  }

  function cleanupOwnObjects(rationale?: string): CompilerCanaryResult {
    const snapshot = reader.snapshot();
    const ownedClipIds = snapshot.clips
      .filter((c) => isOwnedByExtension(c, extensionId))
      .map((c) => c.id);

    if (ownedClipIds.length === 0) {
      return { generatedClipIds: [], sourceMapEntryIds: [] };
    }

    const removeOps: TimelinePatchOperation[] = ownedClipIds.map((id) => ({
      op: 'clip.remove' as const,
      target: id,
    }));

    const patch: TimelinePatch = {
      version: snapshot.baseVersion,
      operations: removeOps,
      source: extensionId,
      meta: { kind: 'compiler-canary-cleanup' },
    };

    const input: TimelineProposalInput = {
      source: extensionId,
      rationale: rationale ?? `Compiler canary cleanup: removing ${ownedClipIds.length} owned clip(s)`,
      patch,
      baseVersion: snapshot.baseVersion,
    };

    const proposal = proposals.create(input);

    return {
      proposal,
      generatedClipIds: [],
      sourceMapEntryIds: [],
    };
  }

  return {
    processDsl,
    cleanupOwnObjects,
    extensionId,
  };
}

/**
 * Create a ReighExtension that wraps the compiler canary.
 *
 * This is the standard defineExtension() shape consumed by the host
 * extension lifecycle.  The activate() function receives the live
 * ExtensionContext and wires up the compiler canary using the creative
 * context services (timeline, reader, proposals).
 *
 * The extension stores its last DSL in settings and can be triggered
 * to re-process by updating the setting.
 */
export function createCompilerCanaryExtension(
  extensionId: string,
  label?: string,
): { manifest: { id: string; version: string; label: string; description: string; apiVersion: number }; activate: (ctx: ExtensionContext) => DisposeHandle } {
  return {
    manifest: {
      id: extensionId,
      version: '1.0.0',
      label: label ?? 'Compiler Canary',
      description: 'M3 compiler canary extension that exercises the full public SDK contract.',
      apiVersion: 1,
    },
    activate(ctx: ExtensionContext): DisposeHandle {
      const canary = createCompilerCanary({
        extensionId,
        timeline: ctx.creative.timeline,
        reader: ctx.creative.reader,
        proposals: ctx.creative.proposals,
      });

      // Read DSL from settings
      const dslJson = ctx.services.settings.get<string>('compiler-canary.dsl');

      let lastResult: CompilerCanaryResult | null = null;

      if (dslJson) {
        lastResult = canary.processDsl(dslJson);
        if (lastResult) {
          ctx.services.diagnostics.report({
            severity: 'info',
            code: 'compiler-canary/processed',
            message: `Compiler canary processed DSL: ${lastResult.generatedClipIds.length} clips generated, proposal ${lastResult.proposal?.id ?? 'none'}`,
          });
        } else {
          ctx.services.diagnostics.report({
            severity: 'warning',
            code: 'compiler-canary/parse-failed',
            message: 'Compiler canary failed to parse DSL from settings.',
          });
        }
      } else {
        ctx.services.diagnostics.report({
          severity: 'info',
          code: 'compiler-canary/no-dsl',
          message: 'Compiler canary activated with no DSL in settings.',
        });
      }

      return {
        dispose(): void {
          // Cleanup only our own generated objects
          canary.cleanupOwnObjects('Extension deactivated — cleaning up owned objects');
          ctx.services.diagnostics.report({
            severity: 'info',
            code: 'compiler-canary/disposed',
            message: 'Compiler canary disposed. Owned objects cleaned up.',
          });
        },
      };
    },
  };
}
